[build]
  command = "pip install -r requirements.txt"
  publish = "public"  # This is less important now but can be left
  functions = "netlify/functions"

[[redirects]]
  from = "/*"  # <-- The change is here
  to = "/.netlify/functions/api/:splat"
  status = 200