[build]
  command = "pip install -r requirements.txt"
  publish = "public"  # This is less important now but can be left
  functions = "netlify/functions"

[[redirects]]
  from = "/*"  # <-- The change is here
  # In netlify.toml, make sure this line is correct:
  to = "/.netlify/functions/app/:splat"
  status = 200